app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://db:5432/booking
      username: postgres
      password: postgres




server:
  error:
    include-binding-errors: always
    include-message: always
